t= (1, 2, 2, 4, 5,5)
count = t.count(1)
print(count)
index = t.index(2)
print(index)
index = t.index(2, 3)
print(index)
s = sum(t)
print("sum is", s)
print("maximum in the tuple", max(t))
print("minimum in the tuple", min(t))
a = (1, 2, 3, 4)
print(sorted(a))
a.sort()
d1 = ()
d2 = ()
s = dict(name="temba", age= "19")//tocreateadictionary
a={'x': 1, 'z': 3, 'y': 2}
print(all(a))
print(any(a))
print(all({}))
print(any({}))
print(all)
y.setdefault('c', 1)
print(y)
('a'